### ISSUE TITLE
Hello, I am using zenika / kotlin, my docker runs docker run -m 100m --memory-swap -1 --cpus '1'

### ISSUE THREAD

**Issue by RanX12** [Zenika/docker-kotlin#48] opened 2019-12-30 04:10 UTC
Hello, I am using zenika / kotlin, my docker runs docker run -m 100m --memory-swap -1 --cpus '1', I do n’t know why it reports this error, can you answer it? ?
/ usr / lib / kotlinc / bin / kotlinc: line 80: 12 Killed "$ {JAVACMD: = java}" $ JAVA_OPTS "$ {java_args [@]}" -cp "$ {kotlin_app [@]}" "$ { kotlin_args [@]} "

**Comment by nlepage** [comment] 2020-01-03 13:36
Hi @RanX12

The options you're giving to `docker run` limit the resources available to the container, which may cause the java process to be killed.

By default kotlinc allows the JVM to use up to 256m of memory, so you cannot limit the available memory to 100m.

Also using `--memory-swap -1` might prevent the process from getting killed, but you're kind of forcing docker to use the swap, which could eventually cause very bad performance.

I'm closing this issue, as the problem is not related to the docker image itself.

**Closed as completed by nlepage** 2020-01-03 13:36 UTC
Labels: question
